-- MySQL Script generated by MySQL Workbench
-- Mon Jan 15 18:04:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Image` (
  `id_Imagen` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Imagen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Data_Set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Data_Set` (
  `id_Data` INT NOT NULL,
  `Date` DATETIME NULL,
  `Time` DATETIME NULL,
  `Site` VARCHAR(45) NULL,
  `id_Imagen` INT NOT NULL,
  PRIMARY KEY (`id_Data`, `id_Imagen`),
  INDEX `fk_Data_Set_Imagen1_idx` (`id_Imagen` ASC) VISIBLE,
  CONSTRAINT `fk_Data_Set_Imagen1`
    FOREIGN KEY (`id_Imagen`)
    REFERENCES `mydb`.`Image` (`id_Imagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Column`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Column` (
  `id_Column` INT NOT NULL,
  `Min` FLOAT NULL,
  `Median` FLOAT NULL,
  `Max` FLOAT NULL,
  `Index` INT NULL,
  PRIMARY KEY (`id_Column`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Statistic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Statistic` (
  `id_Statistic` INT NOT NULL,
  `Min_Absolute` FLOAT NULL,
  `Median_Absolute` FLOAT NULL,
  `Max_Absolute` FLOAT NULL,
  `id_Imagen` INT NOT NULL,
  `id_Column` INT NOT NULL,
  PRIMARY KEY (`id_Statistic`, `id_Imagen`, `id_Column`),
  INDEX `fk_Statistic_Imagen1_idx` (`id_Imagen` ASC) VISIBLE,
  INDEX `fk_Statistic_Column1_idx` (`id_Column` ASC) VISIBLE,
  CONSTRAINT `fk_Statistic_Imagen1`
    FOREIGN KEY (`id_Imagen`)
    REFERENCES `mydb`.`Image` (`id_Imagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Statistic_Column1`
    FOREIGN KEY (`id_Column`)
    REFERENCES `mydb`.`Column` (`id_Column`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`File` (
  `id_Data` INT NOT NULL,
  `id_Column` INT NOT NULL,
  `id_File` INT NOT NULL,
  `Name_Cols` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Data`, `id_Column`, `id_File`),
  INDEX `fk_Data_Set_has_Column_Column1_idx` (`id_Column` ASC) VISIBLE,
  INDEX `fk_Data_Set_has_Column_Data_Set_idx` (`id_Data` ASC) VISIBLE,
  CONSTRAINT `fk_Data_Set_has_Column_Data_Set`
    FOREIGN KEY (`id_Data`)
    REFERENCES `mydb`.`Data_Set` (`id_Data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Data_Set_has_Column_Column1`
    FOREIGN KEY (`id_Column`)
    REFERENCES `mydb`.`Column` (`id_Column`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
